// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Item {
  final String id;
  final String title;
  final String? summary;
  final String? originalUrl;
  final String? coverImageUrl;
  final String? audioUrl;
  final PlatformInt64? publishTime;
  final PlatformInt64? createdAt;
  final int? rating;
  final String? tags;
  final bool? isDeleted;
  final PlatformInt64? durationSec;
  final String? status;
  final String? category;

  const Item({
    required this.id,
    required this.title,
    this.summary,
    this.originalUrl,
    this.coverImageUrl,
    this.audioUrl,
    this.publishTime,
    this.createdAt,
    this.rating,
    this.tags,
    this.isDeleted,
    this.durationSec,
    this.status,
    this.category,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      summary.hashCode ^
      originalUrl.hashCode ^
      coverImageUrl.hashCode ^
      audioUrl.hashCode ^
      publishTime.hashCode ^
      createdAt.hashCode ^
      rating.hashCode ^
      tags.hashCode ^
      isDeleted.hashCode ^
      durationSec.hashCode ^
      status.hashCode ^
      category.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Item &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          summary == other.summary &&
          originalUrl == other.originalUrl &&
          coverImageUrl == other.coverImageUrl &&
          audioUrl == other.audioUrl &&
          publishTime == other.publishTime &&
          createdAt == other.createdAt &&
          rating == other.rating &&
          tags == other.tags &&
          isDeleted == other.isDeleted &&
          durationSec == other.durationSec &&
          status == other.status &&
          category == other.category;
}
