// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FreshLoopClient>>
abstract class FreshLoopClient implements RustOpaqueInterface {
  Future<List<Item>> fetchItems({required int page, required int limit});

  Future<User> login({required String username, required String password});

  Future<void> markAsPlayed({required String id});

  factory FreshLoopClient({required String baseUrl, String? userId}) => RustLib
      .instance
      .api
      .crateApiClientFreshLoopClientNew(baseUrl: baseUrl, userId: userId);

  void setUserId({String? userId});
}

class User {
  final String id;
  final String username;

  const User({required this.id, required this.username});

  @override
  int get hashCode => id.hashCode ^ username.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is User &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          username == other.username;
}
