// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Repository>>
abstract class Repository implements RustOpaqueInterface {
  Future<List<String>> getPlayedIds();

  Future<List<Item>> getQueue();

  Future<void> insertQueue({required List<Item> items});

  Future<void> markPlayed({required String id});

  factory Repository({required String dbPath}) =>
      RustLib.instance.api.crateApiRepositoryRepositoryNew(dbPath: dbPath);
}
